version: '3.2'

services:
    api:
        build: api
        container_name: piston_api
        privileged: true
        restart: always
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        environment:
            - PISTON_REPO_URL=http://repo:8000/index

    repo: # Local testing of packages
        build: repo
        container_name: piston_repo
        command: ['--no-build'] # Don't build anything
        volumes:
            - .:/piston
